/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package com.dexscript.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.dexscript.psi.DexTypes.*;
import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>_DexscriptLexer.flex</tt>
 */
public class _DexscriptLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [7, 7, 7]
   * Total runtime size is 1928 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>14]|((ch>>7)&0x7f)]<<7)|(ch&0x7f)];
  }

  /* The ZZ_CMAP_Z table has 68 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\103\200");

  /* The ZZ_CMAP_Y table has 256 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\53\2\1\3\22\2\1\4\37\2\1\3\237\2");

  /* The ZZ_CMAP_A table has 640 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\5\1\22\0\1\1\1\14\3\0\1\25\1\20\1\0\1\6\1\7\1\23\1\15\1\12\1\16\1\27"+
    "\1\24\12\0\1\10\1\11\1\22\1\13\1\26\15\0\1\31\1\0\1\30\14\0\1\4\1\0\1\5\1"+
    "\21\1\41\1\0\1\37\3\0\1\35\1\0\1\45\1\0\1\43\4\0\1\44\1\0\1\34\1\0\1\36\1"+
    "\42\1\32\2\0\1\40\1\0\1\33\1\0\1\2\1\17\1\3\7\0\1\1\32\0\1\1\337\0\1\1\177"+
    "\0\13\1\35\0\2\1\5\0\1\1\57\0\1\1\40\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\1\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\0\1\51\1\52\1\53\1\54\1\55"+
    "\3\0\1\56\1\57\1\0\1\60\1\61\2\0\1\62"+
    "\1\63\6\0\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\46\0\46\0\46\0\46\0\46"+
    "\0\46\0\162\0\46\0\46\0\230\0\276\0\344\0\u010a"+
    "\0\u0130\0\u0156\0\u017c\0\u01a2\0\u01c8\0\u01ee\0\u0214\0\u023a"+
    "\0\u0260\0\u0286\0\u02ac\0\46\0\46\0\46\0\46\0\46"+
    "\0\46\0\46\0\46\0\46\0\46\0\46\0\u02d2\0\46"+
    "\0\46\0\46\0\u02f8\0\u031e\0\46\0\46\0\46\0\46"+
    "\0\u0344\0\u036a\0\u0390\0\u03b6\0\46\0\46\0\u03dc\0\46"+
    "\0\46\0\u0402\0\u0428\0\46\0\46\0\u044e\0\u0474\0\u049a"+
    "\0\u04c0\0\u04e6\0\u050c\0\46";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\2\2\1\32\3\2\1\33\7\2\47\0\1\3\57\0"+
    "\1\34\45\0\1\35\45\0\1\36\45\0\1\37\1\0"+
    "\1\40\43\0\1\41\2\0\1\42\42\0\1\43\3\0"+
    "\1\44\41\0\1\45\4\0\1\46\1\47\37\0\1\50"+
    "\45\0\1\51\2\0\1\52\3\0\1\53\5\0\1\54"+
    "\30\0\1\55\45\0\1\56\45\0\1\57\45\0\1\60"+
    "\12\0\1\61\46\0\1\62\51\0\1\63\51\0\1\64"+
    "\21\0\1\65\45\0\1\66\63\0\1\67\27\0\1\70"+
    "\61\0\1\71\52\0\1\72\51\0\1\73\33\0\1\74"+
    "\54\0\1\75\51\0\1\76\46\0\1\77\35\0\1\100"+
    "\51\0\1\101\52\0\1\102\46\0\1\103\46\0\1\104";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1330];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\6\11\1\1\2\11\17\1\13\11"+
    "\1\1\3\11\1\1\1\0\4\11\1\1\3\0\2\11"+
    "\1\0\2\11\2\0\2\11\6\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _DexscriptLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _DexscriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return BAD_CHARACTER;
            } 
            // fall through
          case 53: break;
          case 2: 
            { return WHITE_SPACE;
            } 
            // fall through
          case 54: break;
          case 3: 
            { return LBRACE;
            } 
            // fall through
          case 55: break;
          case 4: 
            { return RBRACE;
            } 
            // fall through
          case 56: break;
          case 5: 
            { return LBRACK;
            } 
            // fall through
          case 57: break;
          case 6: 
            { return RBRACK;
            } 
            // fall through
          case 58: break;
          case 7: 
            { return LPAREN;
            } 
            // fall through
          case 59: break;
          case 8: 
            { return RPAREN;
            } 
            // fall through
          case 60: break;
          case 9: 
            { return COLON;
            } 
            // fall through
          case 61: break;
          case 10: 
            { return SEMICOLON;
            } 
            // fall through
          case 62: break;
          case 11: 
            { return COMMA;
            } 
            // fall through
          case 63: break;
          case 12: 
            { return ASSIGN;
            } 
            // fall through
          case 64: break;
          case 13: 
            { return NOT;
            } 
            // fall through
          case 65: break;
          case 14: 
            { return PLUS;
            } 
            // fall through
          case 66: break;
          case 15: 
            { return MINUS;
            } 
            // fall through
          case 67: break;
          case 16: 
            { return BIT_OR;
            } 
            // fall through
          case 68: break;
          case 17: 
            { return BIT_AND;
            } 
            // fall through
          case 69: break;
          case 18: 
            { return BIT_XOR;
            } 
            // fall through
          case 70: break;
          case 19: 
            { return LESS;
            } 
            // fall through
          case 71: break;
          case 20: 
            { return MUL;
            } 
            // fall through
          case 72: break;
          case 21: 
            { return QUOTIENT;
            } 
            // fall through
          case 73: break;
          case 22: 
            { return REMAINDER;
            } 
            // fall through
          case 74: break;
          case 23: 
            { return GREATER;
            } 
            // fall through
          case 75: break;
          case 24: 
            { return DOT;
            } 
            // fall through
          case 76: break;
          case 25: 
            { return VAR_ASSIGN;
            } 
            // fall through
          case 77: break;
          case 26: 
            { return EQ;
            } 
            // fall through
          case 78: break;
          case 27: 
            { return NOT_EQ;
            } 
            // fall through
          case 79: break;
          case 28: 
            { return PLUS_ASSIGN;
            } 
            // fall through
          case 80: break;
          case 29: 
            { return PLUS_PLUS;
            } 
            // fall through
          case 81: break;
          case 30: 
            { return MINUS_ASSIGN;
            } 
            // fall through
          case 82: break;
          case 31: 
            { return MINUS_MINUS;
            } 
            // fall through
          case 83: break;
          case 32: 
            { return BIT_OR_ASSIGN;
            } 
            // fall through
          case 84: break;
          case 33: 
            { return COND_OR;
            } 
            // fall through
          case 85: break;
          case 34: 
            { return BIT_AND_ASSIGN;
            } 
            // fall through
          case 86: break;
          case 35: 
            { return COND_AND;
            } 
            // fall through
          case 87: break;
          case 36: 
            { return BIT_CLEAR;
            } 
            // fall through
          case 88: break;
          case 37: 
            { return BIT_XOR_ASSIGN;
            } 
            // fall through
          case 89: break;
          case 38: 
            { return LESS_OR_EQUAL;
            } 
            // fall through
          case 90: break;
          case 39: 
            { return SEND_CHANNEL;
            } 
            // fall through
          case 91: break;
          case 40: 
            { return SHIFT_LEFT;
            } 
            // fall through
          case 92: break;
          case 41: 
            { return MUL_ASSIGN;
            } 
            // fall through
          case 93: break;
          case 42: 
            { return QUOTIENT_ASSIGN;
            } 
            // fall through
          case 94: break;
          case 43: 
            { return REMAINDER_ASSIGN;
            } 
            // fall through
          case 95: break;
          case 44: 
            { return GREATER_OR_EQUAL;
            } 
            // fall through
          case 96: break;
          case 45: 
            { return SHIFT_RIGHT;
            } 
            // fall through
          case 97: break;
          case 46: 
            { return BIT_CLEAR_ASSIGN;
            } 
            // fall through
          case 98: break;
          case 47: 
            { return SHIFT_LEFT_ASSIGN;
            } 
            // fall through
          case 99: break;
          case 48: 
            { return SHIFT_RIGHT_ASSIGN;
            } 
            // fall through
          case 100: break;
          case 49: 
            { return TRIPLE_DOT;
            } 
            // fall through
          case 101: break;
          case 50: 
            { return SEMICOLON_SYNTHETIC;
            } 
            // fall through
          case 102: break;
          case 51: 
            { return TYPE_;
            } 
            // fall through
          case 103: break;
          case 52: 
            { return RAW_STRING;
            } 
            // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
